apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: chaincode-install-carrier-peer0-1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: chaincode-install-carrier-peer0-1
  chart:
    git: https://github.com/jagpreetsinghsasan/blockchain-automation-framework.git
    ref: cactus
    path: platforms/hyperledger-fabric/charts/install_chaincode
  values:
    metadata:
      namespace: carrier-net
      network:
        version: 1.4.8
      images:
        fabrictools: hyperledger/fabric-tools:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://172.17.0.2:1234
      authpath: localcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      secretgitprivatekey: secret/credentials/carrier-net/git?git_password
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:1.4.8
      name: supplychain
      version: 1
      lang: golang
      maindirectory: cmd
      repository:
        hostname: "github.com"
        git_username: "jagpreetsinghsasan"
        url: github.com/jagpreetsinghsasan/blockchain-automation-framework.git
        branch: cactus
        path: examples/supplychain-app/fabric/chaincode_rest_server/chaincode/
      endorsementpolicies:  ''
