apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: instantiate-carrier-allchannel-supplychain1
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: instantiate-carrier-allchannel-supplychain1
  chart:
    git: https://github.com/jagpreetsinghsasan/blockchain-automation-framework.git
    ref: cactus
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.8
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://172.17.0.2:1234
      authpath: localcarrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:1.4.8
      name: supplychain
      lang: golang
      version: 1
      instantiationarguments: '\"init\",\"\"'
      endorsementpolicies:  ''
    channel:
      name: allchannel